{
 "title": "PI1",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Ultrasonic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"DUS1\" and r._measurement == \"Distance\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"RDHT1\" and r._measurement == \"Temperature\")"
    },
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"RDHT2\" and r._measurement == \"Temperature\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"RDHT1\" and r._measurement == \"Humidity\")"
    },
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"RDHT2\" and r._measurement == \"Humidity\")"
    }
   ]
  },
  {
   "title": "RPIR1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"RPIR1\" and r._measurement == \"Motion\")"
    }
   ]
  },
  {
   "title": "DPIR1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"DPIR1\" and r._measurement == \"Motion\")"
    }
   ]
  },
  {
   "title": "RPIR2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"RPIR2\" and r._measurement == \"Motion\")"
    }
   ]
  },
  {
   "title": "DS1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"DS1\" and r._measurement == \"Button\")"
    }
   ]
  },
  {
   "title": "DMS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"DMS\" and r._measurement == \"Keypad\")"
    }
   ]
  }
 ]
}