{
 "title": "PI2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => (r.codename == \"RDHT3\" or r.codename == \"GDHT\") and r._measurement == \"Humidity\")"
    },
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"RDHT2\" and r._measurement == \"Humidity\")"
    }
   ]
  },
  {
   "title": "Ultrasonic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.codename == \"DUS2\" and r._measurement == \"Distance\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => (r.codename == \"RDHT3\" or r.codename == \"GDHT\") and r._measurement == \"Temperature\")"
    },
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"RDHT2\" and r._measurement == \"Temperature\")"
    }
   ]
  },
  {
   "title": "DPIR2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.codename == \"DPIR2\" and r._measurement == \"Motion\")"
    }
   ]
  },
  {
   "title": "Rotation of GSG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.codename == \"GSG\" and (r._measurement == \"Rotation_x\" or r._measurement == \"Rotation_y\" or r._measurement == \"Rotation_z\"))"
    },
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"RDHT2\" and r._measurement == \"Humidity\")"
    }
   ]
  },
  {
   "title": "Acceleration (g) of GSG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.codename == \"GSG\" and (r._measurement == \"Acceleration_x\" or r._measurement == \"Acceleration_y\" or r._measurement == \"Acceleration_z\"))"
    },
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"RDHT2\" and r._measurement == \"Humidity\")"
    }
   ]
  },
  {
   "title": "DS2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.codename == \"DS2\" and r._measurement == \"Button\")"
    }
   ]
  },
  {
   "title": "RPIR3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.codename == \"RPIR3\" and r._measurement == \"Motion\")"
    }
   ]
  }
 ]
}