{
 "title": "PI3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.codename == \"RDHT4\" and r._measurement == \"Temperature\")"
    },
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"RDHT2\" and r._measurement == \"Temperature\")"
    }
   ]
  },
  {
   "title": "RPIR4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.codename == \"RPIR4\" and r._measurement == \"Motion\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.codename == \"RDHT4\" and r._measurement == \"Humidity\")"
    },
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: -360m)\n|> filter(fn: (r) => r.codename == \"RDHT2\" and r._measurement == \"Humidity\")"
    }
   ]
  },
  {
   "title": "BIR",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"example_db\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.codename == \"BIR\" and r._measurement == \"IRReceiver\")"
    }
   ]
  }
 ]
}